zuihou:
  nginx:
    ip: tangyh.top
    port: 10000
  redis:
    ip: 127.0.0.1
    port: 16379
    password: SbtyMveYNfLzTks7H0apCmyStPzWJqjy
    database: 0
  rabbitmq:
    enabled: false
    ip: 127.0.0.1
    port: 5672
    username: zuihou
    password: zuihou
  mysql:
    ip: 127.0.0.1
    port: 3306
    driverClassName: com.mysql.cj.jdbc.Driver
    database: zuihou_defaults
    username: root
    password: root
  database:
    isNotWrite: true
  swagger:
    # 正式环境用nginx代理，为了保持和cloud版本一致的URL，特意调整
    docket:
      general:
        base-path: /api/oauth
      oauth:
        base-path: /api/oauth
      auth:
        base-path: /api/authority
      common:
        base-path: /api/authority
      core:
        base-path: /api/authority
      tenant:
        base-path: /api/authority
      sms:
        base-path: /api/msgs
      msgs:
        base-path: /api/msgs
      file:
        base-path: /api/file
