zuihou:
  nginx:
    ip: 127.0.0.1      # 正式环境需要将该ip设置成nginx对应的 公网ip
    port: 10000
  redis:
    ip: 127.0.0.1
    port: 16379
    password: SbtyMveYNfLzTks7H0apCmyStPzWJqjy
    database: 0
  rabbitmq:
    enabled: false
    ip: 127.0.0.1
    port: 5672
    username: zuihou
    password: zuihou
  mysql:
    ip: 127.0.0.1
    port: 3306
    driverClassName: com.mysql.cj.jdbc.Driver
    database: zuihou_defaults
    username: root
    password: root
    url: jdbc:mysql://${zuihou.mysql.ip}:${zuihou.mysql.port}/${zuihou.mysql.database}?serverTimezone=CTT&characterEncoding=utf8&useUnicode=true&useSSL=false&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&nullCatalogMeansCurrent=true
  database:
    tenantDatabasePrefix: zuihou_boot
    multiTenantType: SCHEMA
    isNotWrite: false
    isBlockAttack: false  # 是否启用 攻击 SQL 阻断解析器
    isSeata: false
    id-type: CACHE
    cache-id:
      time-bits: 31
      worker-bits: 22
      seq-bits: 10
      epochStr: '2020-09-15'
      boost-power: 3
      padding-factor: 50
  injection:
    # 是否启用 远程数据 手动注入
    enabled: true
    # 是否启用 远程数据 注解注入
    aop-enabled: true
    guavaCache:
      enabled: true
      maximumSize: 1000
      refreshWriteTime: 10
      refreshThreadPoolSize: 1000
  security:
    # 是否开启URI权限校验
    enabled: true
    type: SERVICE
  log:
    enabled: true
    type: DB
  context:
    # 上下文拦截器
    pathPatterns: '/**'
    order: -20
  file:
    type: LOCAL # FAST_DFS LOCAL
    storage-path: /data/projects/uploadfile/file/     # 文件存储路径  （ 某些版本的 window 需要改成  D:\\data\\projects\\uploadfile\\file\\  ）
    uriPrefix: http://${zuihou.nginx.ip}:${zuihou.nginx.port}/file/   # 文件访问 需要通过这个uri前缀进行访问
    inner-uri-prefix: null  #  内网的url前缀
    down-by-id: http://${zuihou.nginx.ip}:${zuihou.nginx.port}/api/file/attachment/download?ids[]=%s
    down-by-biz-id: http://${zuihou.nginx.ip}:${zuihou.nginx.port}/api/file/attachment/download/biz?bizIds[]=%s
    down-by-url: http://${zuihou.nginx.ip}:${zuihou.nginx.port}/api/file/attachment/download/url?url=%s&filename=%s
    ali:
      # 请填写自己的阿里云存储配置
      uriPrefix: http://test.oss-cn-shenzhen.aliyuncs.com/
      bucket-name: test
      endpoint: http://oss-cn-shenzhen.aliyuncs.com
      access-key-id: test
      access-key-secret: test
  swagger:
    license: Powered By zuihou
    licenseUrl: https://github.com/zuihou
    termsOfServiceUrl: https://github.com/zuihou
    version: @project.version@
    global-operation-parameters:
      - name: token
        description: 用户身份token
        modelRef: String
        parameterType: header
        required: true
        # 默认值只是方便本地开发时，少填参数，生产环境请禁用swagger或者禁用默认参数
        defaultValue: "Bearer test"
      - name: Authorization
        description: 客户端信息
        modelRef: String
        parameterType: header
        required: true
        defaultValue: "Basic enVpaG91X3VpOnp1aWhvdV91aV9zZWNyZXQ="
      - name: tenant
        description: 租户编码
        modelRef: String
        parameterType: header
        required: true
        defaultValue: "MDAwMA=="
    docket:
      general:
        title: 通用模块
        base-package: com.github.zuihou.general.controller
      oauth:
        title: 认证模块
        base-package: com.github.zuihou.oauth.controller
      auth:
        title: 权限模块
        base-package: com.github.zuihou.authority.controller.auth
      common:
        title: 公共模块
        base-package: com.github.zuihou.authority.controller.common
      core:
        title: 组织模块
        base-package: com.github.zuihou.authority.controller.core
      tenant:
        title: 租户模块
        base-package: com.github.zuihou.tenant.controller
      sms:
        title: 短信模块
        base-package: com.github.zuihou.sms.controller
      msgs:
        title: 消息模块
        base-package: com.github.zuihou.msgs.controller
      mail:
        title: 邮件模块
        base-package: com.github.zuihou.mail.controller
      file:
        title: 文件服务
        base-package: com.github.zuihou.file.controller

authentication:
  expire: 28800               # token有效期为8小时
  refreshExpire: 86400        # 刷新token有效期为24小时

server:
  port: 8760
  undertow:
    io-threads: 8 # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
    worker-threads: 120  # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
    buffer-size: 2048  # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理 , 每块buffer的空间大小,越小的空间被利用越充分
    direct-buffers: true  # 是否分配的直接内存

dozer:
  mappingFiles:
    - classpath*:dozer/*.dozer.xml

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
      enabled: true

spring:
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  servlet:
    multipart:
      max-file-size: 512MB      # Max file size，默认1M
      max-request-size: 512MB   # Max request size，默认10M
  rabbitmq:
    enabled: ${zuihou.rabbitmq.enabled}
    host: ${zuihou.rabbitmq.ip}
    port: ${zuihou.rabbitmq.port}
    username: ${zuihou.rabbitmq.username}
    password: ${zuihou.rabbitmq.password}
    listener:
      type: direct # simple direct
  redis:
    host: ${zuihou.redis.ip}
    password: ${zuihou.redis.password}
    port: ${zuihou.redis.port}
    database: ${zuihou.redis.database}
  cache:
    type: GENERIC
  datasource:
    # 从这里开始(dynamic)，中间的这段配置用于 zuihou.database.multiTenantType == DATASOURCE 时
    # 联系作者 购买太懂
    # 从这里结束(dynamic)，中间的这段配置用于 zuihou.database.multiTenantType == DATASOURCE 时
    druid:
      enable: true
      # 从这里开始(druid)，中间的这段配置用于 zuihou.database.multiTenantType != DATASOURCE 时
      username: ${zuihou.mysql.username}
      password: ${zuihou.mysql.password}
      driver-class-name: ${zuihou.mysql.driverClassName}
      url: jdbc:mysql://${zuihou.mysql.ip}:${zuihou.mysql.port}/${zuihou.mysql.database}?serverTimezone=CTT&characterEncoding=utf8&useUnicode=true&useSSL=false&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&nullCatalogMeansCurrent=true
      db-type: mysql
      initialSize: 10
      minIdle: 10
      maxActive: 500
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      validation-query: SELECT 'x'
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000  #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 300000    #配置一个连接在池中最小生存的时间，单位是毫秒
      filters: stat,wall
      filter:
        wall:
          enabled: true
          config:
            commentAllow: true
            multiStatementAllow: true
            noneBaseStatementAllow: true
      # 从这里结束(druid)，中间的这段配置用于 zuihou.database.multiTenantType != DATASOURCE 时

      # 以下的2段配置，同时适用于所有模式
      web-stat-filter:  # WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
        enabled: true
        url-pattern: /*
        exclusions: "*.js , *.gif ,*.jpg ,*.png ,*.css ,*.ico , /druid/*"
        session-stat-max-count: 1000
        profile-enable: true
        session-stat-enable: false
      stat-view-servlet:  #展示Druid的统计信息,StatViewServlet的用途包括：1.提供监控信息展示的html页面2.提供监控信息的JSON API
        enabled: true
        url-pattern: /druid/*   #根据配置中的url-pattern来访问内置监控页面，如果是上面的配置，内置监控页面的首页是/druid/index.html例如：http://127.0.0.1:9000/druid/index.html
        reset-enable: true    #允许清空统计数据
        login-username: zuihou
        login-password: zuihou

mybatis-plus:
  mapper-locations:
    - classpath*:mapper_**/**/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.github.zuihou.*.entity;com.github.zuihou.database.mybatis.typehandler
  typeEnumsPackage: com.github.zuihou.*.enumeration
  global-config:
    db-config:
      id-type: INPUT
      insert-strategy: NOT_NULL
      update-strategy: NOT_NULL
      select-strategy: NOT_EMPTY
  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    cache-enabled: false
    #配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: 'null'

j2cache:
  #  config-location: /j2cache.properties
  open-spring-cache: true
  cache-clean-mode: passive
  allow-null-values: true
  redis-client: lettuce
  l2-cache-open: true
  # l2-cache-open: false     # 关闭二级缓存
  broadcast: net.oschina.j2cache.cache.support.redis.SpringRedisPubSubPolicy
  #  broadcast: jgroups       # 关闭二级缓存
  L1:
    provider_class: caffeine
  L2:
    provider_class: net.oschina.j2cache.cache.support.redis.SpringRedisProvider
    config_section: lettuce
  sync_ttl_to_redis: true
  default_cache_null_object: false
  serialization: fst
caffeine:
  properties: /j2cache/caffeine.properties   # 这个配置文件需要放在项目中
lettuce:
  mode: single
  namespace: ''
  storage: generic
  channel: j2cache
  scheme: redis
  hosts: ${zuihou.redis.ip}:${zuihou.redis.port}
  password: ${zuihou.redis.password}
  database: ${zuihou.redis.database}
  sentinelMasterId: ''
  maxTotal: 100
  maxIdle: 10
  minIdle: 10
  timeout: 10000

# 用于/actuator/info
info:
  name: '@project.name@'
  description: '@project.description@'
  version: '@project.version@'
  spring-boot-version: '@spring.boot.version@'
